# Generated by Django 5.1.6 on 2025-03-12 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='p_name',
            new_name='productname',
        ),
    ]
