# Generated by Django 5.1.6 on 2025-03-13 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0002_rename_p_name_products_productname'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='numReview',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
